# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "GameFunctionsStack"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_prefix = "GameActionHandler"
region = "us-east-1"
profile = "prod"
image_repositories = []
stack_name = "GameActionHandlerStack"
parameter_overrides = "CodeUri=\"ActionHandler-202507071346.zip\""

[default.package.parameters]
#resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

#[prod.deploy.parameters]
#stack_name = "GameFunctionsStack"
##resolve_s3 = true
#s3_prefix = "GameFunctionsStack"
#region = "us-east-1"
#profile = "prod"
#confirm_changeset = true
#capabilities = "CAPABILITY_IAM"
#image_repositories = []
