AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Game Action Handler

  Sample SAM Template for game actions

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:

  WebGamesWebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: WebGamesWebSocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebGamesWebSocketApi
      StageName: ws
      AutoDeploy: true

  ActionHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      FunctionName: ActionHandler
      ImageUri: 841027546523.dkr.ecr.us-east-1.amazonaws.com/lambda-native/action-handler:20250627173034
      Architectures: [ x86_64 ]
      Policies:
        - Statement:
            - Effect: Allow
              Action: execute-api:ManageConnections
              Resource: arn:aws:execute-api:*:*:*/*/POST/@connections/*

  ActionHandlerIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebGamesWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ActionHandlerFunction.Arn}/invocations
      IntegrationMethod: POST
  ActionHandlerRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebGamesWebSocketApi
      RouteKey: $default
      Target: !Sub integrations/${ActionHandlerIntegration}
  ActionHandlerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ActionHandlerFunction
      Principal: apigateway.amazonaws.com



Outputs:
  WebSocketApiEndpoint:
    Description: "WebSocket API Endpoint URL"
    Value: !Sub "wss://${WebGamesWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/ws"
  ActionHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for ActionHandlerFunction"
    Value: !GetAtt ActionHandlerFunctionRole.Arn
